mqtt_servers:
  server1:
    broker: s3550ec0.ala.us-east-1.emqxsl.com
    port: 8883
    username: Pengvin1
    password: Pengvin1
    ca_cert: /Users/nemasis/Downloads/emqxsl-ca (1).crt
    client_id_prefix: AlertMonitor_Pengvin
    keepalive: 60


  alert_publisher:
    broker: s3550ec0.ala.us-east-1.emqxsl.com
    port: 8883
    username: Alert  # Use Pengvin1 credentials for publishing alerts
    password: Alert
    ca_cert: /Users/nemasis/Downloads/emqxsl-ca (1).crt
    client_id_prefix: AlertPublisher
    keepalive: 60

routes:
- topic: Pengvin1
  mqtt_server: server1


# Database configuration for threshold management
database:
  uri: postgresql://admin:password@db.telemetrywatch.com:5432/unified_ingestion
  # Connection pool settings
  pool_size: 5
  max_overflow: 10

# Company and device mapping for database integration
company_config:
  # Map MQTT topics to company IDs
  topic_company_mapping:
    Pengvin1: 1


# Alert monitoring configuration
alerts:
  enabled: true
  alert_topic: "alerts/monitoring"
  mqtt_server: alert_publisher  # Dedicated server for publishing alerts
