mqtt_servers:
  server1:
    broker: s3550ec0.ala.us-east-1.emqxsl.com
    port: 8883
    username: Pengvin1
    password: Pengvin1
    ca_cert: /Users/nemasis/Downloads/emqxsl-ca (1).crt
    client_id_prefix: Diffcalculator
    keepalive: 60
    workers: 16  # Increased from default 4 to handle high device volume

  server2:
    broker: s3550ec0.ala.us-east-1.emqxsl.com
    port: 8883
    username: Gree1
    password: Gree1
    ca_cert: /Users/nemasis/Downloads/emqxsl-ca (1).crt
    client_id_prefix: Differencecalculator
    keepalive: 60
    workers: 20  # Increased from default 4 - Gree has most devices (~103)

  server3:
    broker: s3550ec0.ala.us-east-1.emqxsl.com
    port: 8883
    username: Energy1
    password: Energy1
    ca_cert: /Users/nemasis/Downloads/emqxsl-ca (1).crt
    client_id_prefix: Differencecalculator
    keepalive: 60
    workers: 12  # Increased from default 4 for Energy devices

database:
  uri: postgresql://admin:password@db.telemetrywatch.com:5432/unified_ingestion
  # Connection pool settings for high-volume processing
  pool_size: 20
  max_overflow: 30
  pool_pre_ping: true
  pool_recycle: 3600

# NEW: Global interval difference configuration
interval_difference:
  enabled: true
  default_frequency_minutes: 5

patterns:
  - name: flat_series_4_params
    match:
      keys:
        - DeviceID
        - Date
        - Time
        - P0
    table: '{topic}_4_difference'
    columns: auto
  - name: flat_series_5_params
    match:
      keys:
        - DeviceID
        - Date
        - Time
        - P0
        - P1
        - P2
        - P3
    table: '{topic}_5_difference'
    columns: auto
    transformations:
      - name: combine_decimal_parts
        condition:
          topic: Energy1
        action:
          type: combine_decimal
          integer_field: P0
          fractional_field: P1
          target_field: P0
          remove_fractional: true
  - name: flat_series_9_params
    match:
      keys:
        - DeviceID
        - Date
        - Time
        - P0
        - P1
        - P2
        - P3
        - P4
        - P5
    table: '{topic}_9_difference'
    columns: auto
  - name: array_enveloped
    match:
      schema:
        root: object
        fields:
          d: object
          ts: string
    table: '{topic}_array_enveloped'
    columns: auto

routes:
- topic: Pengvin1
  mqtt_server: server1
  auto_discover: true
  device_ids:
    - pattern: '*'
      # Let pattern matching decide automatically
  # NEW: Optional interval difference configuration for this topic
  interval_difference:
    enabled: true
    frequency_minutes: 5
    table_suffix: "_interval_diff"  # Creates pengvin1_5_interval_diff table for 5-param messages

  # - topic: Gree1
  #   mqtt_server: server2
  #   auto_discover: true
  #   device_ids:
  #     - pattern: '*'
  #       # Let pattern matching decide automatically
  #   # NEW: Optional interval difference configuration for this topic
  #   interval_difference:
  #     enabled: false
  #     frequency_minutes: 5
  #     table_suffix: "_interval_diff"  # Creates pengvin1_5_interval_diff table for 5-param messages

  #- topic: Energy1
   # mqtt_server: server3
   # auto_discover: true
   # device_ids:
      #- pattern: '*'
        # Let pattern matching decide automatically
    # NEW: Optional interval difference configuration for this topic
    #interval_difference:
     # enabled: true
      #frequency_minutes: 5
     # table_suffix: "_interval_diff"  # Creates pengvin1_5_interval_diff table for 5-param messages