mqtt_servers:
  server1:
    broker: s3550ec0.ala.us-east-1.emqxsl.com
    port: 8883
    username: Gree1
    password: Gree1
    ca_cert: /Users/nemasis/Downloads/emqxsl-ca (1).crt
    client_id_prefix: UnifiedIngestor
    keepalive: 60


database:
  uri: postgresql://admin:password@db.telemetrywatch.com:5432/unified_ingestion

patterns:
  - name: flat_series_4_params
    match:
      keys:
        - DeviceID
        - Date
        - Time
        - P0
    table: '{topic}_4'
    columns: auto
  - name: flat_series_5_params
    match:
      keys:
        - DeviceID
        - Date
        - Time
        - P0
        - P1
    table: '{topic}_5'
    columns: auto
    transformations:
      - name: combine_decimal_parts
        condition:
          topic: Energy1
        action:
          type: combine_decimal
          integer_field: P0
          fractional_field: P1
          target_field: P0
          remove_fractional: true
  - name: flat_series_9_params
    match:
      keys:
        - DeviceID
        - Date
        - Time
        - P0
        - P1
        - P2
        - P3
        - P4
        - P5
    table: '{topic}_9'
    columns: auto
  - name: array_enveloped
    match:
      schema:
        root: object
        fields:
          d: object
          ts: string
    table: '{topic}_array_enveloped'
    columns: auto

routes:

  - topic: Gree1
    mqtt_server: server1
    auto_discover: true
    device_ids:
      - pattern: '*'
        # Let pattern matching decide automatically
  - topic: Energy1
    mqtt_server: server1
    auto_discover: true
    device_ids:
      - pattern: '*'
        pattern_name: flat_series_5_params

  